#pragma once

// Application icon – lowest numeric ID so Windows picks it as the default
// executable icon in Explorer.
#define IDI_HYPERBROWSE  1
#define IDB_HYPERBROWSE_BRAND_PNG  101
#define IDR_TOOLBAR_ICON_OPEN_FOLDER  201
#define IDR_TOOLBAR_ICON_RECURSIVE  202
#define IDR_TOOLBAR_ICON_VIEW_GRID  203
#define IDR_TOOLBAR_ICON_VIEW_LIST  204
#define IDR_TOOLBAR_ICON_SORT  205
#define IDR_TOOLBAR_ICON_THUMBNAIL_SIZE  206
#define IDR_TOOLBAR_ICON_COPY  207
#define IDR_TOOLBAR_ICON_MOVE  208
#define IDR_TOOLBAR_ICON_DELETE  209
#define IDR_TOOLBAR_ICON_SEARCH  210
#define IDR_TOOLBAR_ICON_CHEVRON_DOWN  211
